### ISSUE TITLE
Consider implementing heudiconv's `--bids notop` option

### ISSUE THREAD

**Issue by loj** [psychoinformatics-de/cbbs-imaging-container-import#13]
heudiconv's `--bids notop` prevents the creation of the BIDS template files, both top level files (README, CHANGES, dataset_description.json) as well as the subject level events.tsv files. But, it also prevents the creation of the participants files.

Right now there are a lot of work-a rounds implemented in `heudiconv-procedure.py` to get rid of these template files. Using `notop` would make this a lot simpler. Downside is that it turns everything off, even helpful files (like the participant files).

@bpoldrack, what are your thoughts on this?

**Comment by bpoldrack** [comment]
Related:
https://github.com/psychoinformatics-de/datalad-hirni/issues/166

**Comment by bpoldrack** [comment]
Note: This would also affect top-level `task_whatever.json` files. However, they arent required in BIDS, if they are available at the subject level.

**Comment by bpoldrack** [comment]
I'm on this again, and I think the loss of actually useful (sidecar) files outweighs the simplicity of `-b notop`.

Note: That this might change if/when heudiconv provides a way to select what is generated (no stupid templates, but all the files that heudiconv can meaningfully fill).

Thus closing here and the respective PR, @loj.
